### PR TITLE
Create Hacking

### PR DESCRIPTION
**Pull request by Sydney6677**
Bitcoin phrases

### CODE REVIEW

**Comment by Warrobot10** [comment]
What are you even doing?

**Comment by Obobamoses2000** [comment]
How a get a private key

**Review by S-code652 — APPROVED** [review]

**Review by euro12234 — APPROVED** [review]

**Review by euro12234 — APPROVED** [review]

**Comment by euro12234** [comment]
How can I crack the code to get the phrase. It’s very hard

**Comment by Dalmorefrank** [comment]
How do I start cracking a wallet?

**Pull request closed without merging**
